services:
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:3.5.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  seed_app:
    build: .
    container_name: seed_app
    env_file: .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - SEED_N=${SEED_N}
      - SEED_BATCH=${SEED_BATCH}
      - SEED_WORKERS=${SEED_WORKERS}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    depends_on:
      - kafka
    restart: "no"

